version: "3.8"

services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
    env_file:
      - .env
    # Connect using hostname 'mongo'
    networks:
      - app-network

  mongo:
    image: mongo:latest
    networks:
      - app-network
    ports:
      - "27017:27017"

networks:
  app-network:
